### ISSUE TITLE
MySQL/MariaDB - ROLLBACK not working

### ISSUE THREAD

**Issue by Jay-UdS** [microsoft/azuredatastudio-mysql#100]
Hello, i have an issue using a typical MySQL/MariaDB 'START TRANSACTION' statement.

I'm using 'SET autocommit = 0' to disable autocommit (works well)
and then a 'ROLLBACK', wich looks to have no effect in Azure Data Studio :-/

I also tryed my script with some other IDEs, and it works fine on both MySQL and MariaDB (see attached).
[MariaDB__AUTOCOMIT-COMMIT-ROLLBACK.sql.txt](https://github.com/microsoft/azuredatastudio-mysql/files/10362820/MariaDB__AUTOCOMIT-COMMIT-ROLLBACK.sql.txt)

Did i missed something with Azure Data Studio connection settings or is that a bug on the connector ?

Regards

**Comment by nitishsharma25** [comment]
Thanks @Jay-UdS for reporting this. This is a bug on the connector. Will be fixed in the next release.

**Comment by Jay-UdS** [comment]
Hello, have you got any information about a possible bugfix ?

Best regards

**Comment by nitishsharma25** [comment]
@Jay-UdS we are planning a new release soon, it will be fixed in that.

**Comment by Jay-UdS** [comment]
Thanks @nitishsharma25

**Comment by nitishsharma25** [comment]
@Jay-UdS  meanwhile, you can install Azure Data Studio-insiders and use mysql extension there, we have released the latest version there.

**Comment by nitishsharma25** [comment]
@Jay-UdS We have released the latest version 0.2.6 with this fix.
