### ISSUE TITLE
Can't configure multiple MariaDB/MySQL instances on different ports

### ISSUE THREAD

**Issue by Jay-UdS** [microsoft/azuredatastudio-mysql#101]
Hello, 

When setting up the connections, if you try to configure multiple MariaDB/MySQL instances, the 1rst connection is overwriten.

Senario: 2 instances of both MariaDB and MySQL on localhost
- 1 connection to MariaDB on port 3306
- 1 connection to MySQL on port 3307

If you force the .json setting manualy, both connections settings are handled (no sure it stay like this for long), but both connections are opened at the same time when you click on 1 of those (and the 2nd server tree is not displayed).

<img width="570" alt="2023-01-06 15_47_21-settings json - SDTDEOPE-414 - Azure Data Studio  Administrator" src="https://user-images.githubusercontent.com/122049895/211100278-1dc3cdf7-75e4-454a-8be4-bf6b32c260a9.png">

I tested here with 2 diffrents RDMS instances (MariaDB and MySQL) thru Docker, but I meet the the same issue with multiple instances of MariaDB, thru network, with diffrent ports.

Regards

**Comment by nitishsharma25** [comment]
Thanks @Jay-UdS, will look into this.

**Comment by nitishsharma25** [comment]
Released 0.2.6 with the fix.
