### ISSUE TITLE
Password saved on one connection overwrites ALL passwords on every other connection

### ISSUE THREAD

**Issue by reukiodo** [microsoft/azuredatastudio-mysql#116]
Issue Type: <b>Bug</b>

1. Run several instances of mysql on localhost, all on different ports
0. set up the same username on each database
0. set different passwords for that username in each different database
0. set up respective server connections in Azure Data Studio for each database with respective usernames passwords (and Remember Password)
0. connect to each database
0. close Azure studio
0. open Azure studio and attemp to connect to each DB again
0. notice that the password send to each DB is identical, not the unique one saved with the connection

Extension version: 0.2.5
Azure Data Studio version: azuredatastudio 1.41.0 (Universal) (cf5e0fe1a33709e2a82dc94f42dbe88487803d62, 2023-01-24T17:29:04.297Z)
OS version: Darwin arm64 22.3.0
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|5, 4, 5|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by nitishsharma25** [comment]
Thanks @reukiodo for reporting this, will look into it.

**Comment by nitishsharma25** [comment]
@reukiodo this issue should have been fixed by https://github.com/microsoft/azuredatastudio-mysql/pull/105, can you please try it again with latest version of MySQL extension in ADS and confirm if you are still facing it

**Comment by reukiodo** [comment]
downloading all updates to validate now (haven't even opened ADS since then)

**Comment by reukiodo** [comment]
<img width="2168" alt="image" src="https://user-images.githubusercontent.com/5169351/233487323-a221d18a-e05c-4cfe-82e1-ddab923a3256.png">

yay! fixed!

I can save unique passwords for all separate dbs on localhost (different ports) and after closing and re-opening ADS, reconnect to each one without re-inputting any passwords!
