### ISSUE TITLE
Server explorer shows list of tables unsorted

### ISSUE THREAD

**Issue by mkn-trumpf** [microsoft/azuredatastudio-mysql#137]
When I want to explore the tables on my MariaDB server
the list of tables is not sorted alphabeticaly. This is very confusing.
I'm using the addin version 0.2.6
Server version is: 10.3.36-MariaDB-1:10.3.36+maria~ubu2004
<img width="153" alt="image" src="https://user-images.githubusercontent.com/89680452/220065376-d8910386-871f-4bdd-b3cd-e611de3fd8ae.png">

**Comment by kpconnell** [comment]
Also experiencing this.  They appear to be displayed in the order the unsorted information_schema.tables but I think most folks would prefer alpha numeric sort.

**Comment by nitishsharma25** [comment]
@mkn-trumpf @kpconnell we have identified the issue and have fixed it, will be released in the next version.
