### ISSUE TITLE
MySql connection not uncollapse, unable to see databases and other objects

### ISSUE THREAD

**Issue by eduardlorente** [microsoft/azuredatastudio-mysql#160]
Using MySql connections, sometimes, I can't uncollapse the connection and I'm unable to see the folders, datases, system databases, users, events, etc.

If I restart Azure data studio it works fine.

<html>
<body>

CPUs | 12th Gen Intel(R) Core(TM) i7-12700H (20 x 2688)
-- | --
GPU Status | 2d_canvas: enabled canvas_oop_rasterization: disabled_off direct_rendering_display_compositor: disabled_off_ok gpu_compositing: enabled multiple_raster_threads: enabled_on opengl: enabled_on rasterization: enabled raw_draw: disabled_off_ok skia_renderer: enabled_on video_decode: enabled video_encode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled webgpu: disabled_off
Load (avg) |  
Memory (System) | 31.70GB (7.43GB free)
Process Argv |  
Screen Reader | no
VM | 0%

<html>
<body>

Extension | Author (truncated) | Version
-- | -- | --
azuredatastudio-mysql | Mic | 0.2.6
query-history | Mic | 0.5.3
extra-sql-script-as | pac | 0.5.0
sql-search | Red | 0.4.2
poor-sql-formatter | WSR | 0.1.0

</body>
</html>

**Comment by nitishsharma25** [comment]
@eduardlorente can you please provide the steps for reproducing or any log file when you face this issue.

**Comment by eduardlorente** [comment]
I have tried to reproduce the error several times but now I can't. Maybe the latest updates have fixed it.
