### ISSUE TITLE
MariaDB vs MySQL connector (BEGIN NOT ATOMIC not handled)

### ISSUE THREAD

**Issue by Jay-UdS** [microsoft/azuredatastudio-mysql#167]
Hello ADS Team, 
well... that's more a question than a real issue. 

I use Azure Data Studio with the MySQL connector, to work on sevral MariaDB databases. 

It looks like **BEGIN NOT ATOMIC** statement is not suported by the connector (and maybe aloso **DELIMITER** ??), witch are handled by MariaDB. 

code example:
```
DELIMITER $$
BEGIN NOT ATOMIC

    IF 1 = 1 THEN
    	SELECT 'Hello';
    END IF;
   
END
$$
DELIMITER ;
```
 
I imagine that's **_"normal" because this is a MySQL connector (not a MariaDB connector)_**, and some specific syntaxes are not compatible between both RDMS.

**_Question :_**
Have you planed to develop a specific MariaDB connector, that handle specific MariaDB syntax, not supported in MySQL ? 
(ex: BEGIN NOT ATOMIC, for anonymous blocks)

I can see there is also an opened issue about this https://github.com/microsoft/azuredatastudio-mysql/issues/90

Thanks in advance for your reply :-)
Regards

**Comment by nitishsharma25** [comment]
Hi @Jay-UdS, we are currently not working on a specific MariaDB connector.

**Comment by Jay-UdS** [comment]
Ok, domage :-(
@nitishsharma25, thanks for your reply.
