### ISSUE TITLE
A11y_MySQLextensionforAzureDataStudio_Connect to a MySQL Server_ Screen Reader: When we navigate to the Server Required field, which is blank, the Screen reader announces "Invalid."

### ISSUE THREAD

**Issue by VijayaBharathyA** [microsoft/azuredatastudio-mysql#192]
"[Check out Accessibility Insights! ](https://accessibilityinsights.io/)- Identify accessibility bugs before check-in and make bug fixing faster and easier.”
### GitHub Tags:
#A11yMAS; #A11yTCS; #A11ySev3; #DesktopApp; #GH-MySQLextensionforAzureDataStudio-Win32-Mar23; #MySQL extension for Azure Data Studio; #Win32; #Info and Relationships; #JAWS; #Screen Reader; #Benchmark; #AILimited;   #Element:Editfield: #NVDA; #JAWS;

**"Please do not close this bug. This bug should only be closed by TCS, C+AI Accessibility or the Divisional Driver."**
### Environment and OS details:
Azure Data Studio Version: 1.42.0 (user setup)
Windows 11 Enterprise Version	22H2
Installed on	‎28-‎12-‎2022
OS build	22621.1413
Experience	Windows Feature Experience Pack 1000.22639.1000.0
NVDA Version 2023.1
JAWS Version 2023
### Pre-Requisite:

1. Install Azure data studio From here https://learn.microsoft.com/en-us/sql/azure-data-studio/download-azure-data-studio?view=sql-server-ver16&tabs=redhat-install%2Credhat-uninstall
2. Once installation done , Install MySQL Extension in Azure data studio
3. Tab Till  new connection and press enter 
4. Enter a valid server name username and password and press connect
### Repro Steps:

1. Launch Azure Data Studio.
2. Turn on NVDA
3. Tab till New connection and Press enter
4. Tab till Server
5.  Verify that Narrator is announcing Invalid entry or not

### Actual Result:
When we navigate to the Server Required field, which is blank, the NVDA announces "Invalid."
**Issue Repro with JAWS Also**
**Notes**
Similar issue repro in Following Screen also
### New Data Base :
1. Launch Azure Data Studio.
2. Connect to server.
3. In the Connections pane, right-click on a server connection. 
4. Then select 'Manage' from the context menu to view the dashboard.
5. From dashboard, click on New Database.
6. Tab till Name and Verify Screen reader is announcing Invalid or not.
### New deployment - Azure Database for MySQL
1. Launch Azure Data Studio.
2. Select the Connections icon (if not already selected) from left bar.
3. Click on the ellipses '...' and select "New Deployment"
4. In the Deployment options, select "Azure Database For MySQL" card.
5.Verify Screen reader is announcing invalid for accept terms of use checkbox or not
### Expected Result:
NVDA should not announce as an invalid entry.
### Attachment:
**Title Issue :**
![main issue2](https://user-images.githubusercontent.com/100189407/229813030-747b1f02-b384-40c1-ae27-966718f4561c.png)

![Screenshot (74)](https://user-images.githubusercontent.com/100189407/229688666-a111aae2-51ee-47a8-9d06-ca07b031319a.png)

**Notes Issue 1:**
![notes issue 1 nvda](https://user-images.githubusercontent.com/100189407/229813290-b678e530-ef5b-4611-b0cf-61f073bfb467.png)

![Screenshot (78)](https://user-images.githubusercontent.com/100189407/229688862-b4451545-afd2-444a-b742-1dd799d7bae8.png)

**Notes Issue 2:**
![Screenshot (59)](https://user-images.githubusercontent.com/100189407/229813629-0db495d9-7043-44e3-8bba-7cb0a26f9f28.png)

![Screenshot (75)](https://user-images.githubusercontent.com/100189407/229688660-46026e83-364c-482f-ba25-cceaa36f7abc.png)

**Comment by nitishsharma25** [comment]
This issue is external to MySQL extension as it is a common UI of Azure Data Studio.

**Comment by VijayaBharathyA** [comment]
External Existing bug Found :https://github.com/microsoft/azuredatastudio/issues/22220

Could You please Reopen the bug since We have follow External process for this bug As per the [External Bug process](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2f%2fmicrosoft.sharepoint.com%2fteams%2fcea11y%2fSitePages%2fExternal-Bug-Process.aspx&data=05%7c01%7cv-vijayaa%40microsoft.com%7c14c77b3db125492f1de008da6f81407a%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637944898905475204%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c3000%7c%7c%7c&sdata=j%2fZFhj1SD8VC%2feIHQIBudkHe8CyIVJpCI6O%2fU73SNNU%3D&reserved=0),
Once external bug is resolved and closed, we will act on this bug accordingly.Please don't close the bug

**Comment by keerthiduvvuri** [comment]
GithubTags:#ResolvedByTT
