### ISSUE TITLE
Cannot open multiple connections to the same server in object explorer

### ISSUE THREAD

**Issue by aasimkhan30** [microsoft/azuredatastudio-mysql#200]
The reason for this issue is that the postgres extension sends a malformed session create response to ads. This malformed response prevents ads from creating a new session. A similar issue can also be found in the Postgres extension. The session create response from the extension is just a Boolean value. 

Expected response: 
```
{
   sessionId: 'session id of the session'
}
```

Actual response from the extension:
```
false
```

To repro:

1. Make 2 server groups
2. Create a connection to the server in one server group
3. Create a connection to the same server in second server group
4. Try to connect both of them.
5. The connection that is trying to connect last will fail

**Comment by aasimkhan30** [comment]
Isssue for Postgres: https://github.com/microsoft/azuredatastudio-postgresql/issues/355

**Comment by rishky-msft** [comment]
@aasimkhan30 
Are you facing this issue in MySQL Extension?

**Comment by aasimkhan30** [comment]
Yes. I am facing this issue in both Postgres and mysql extensions. 
![image](https://user-images.githubusercontent.com/6816294/230293519-94f6e444-dfe3-4e6f-8c81-86c8be5979aa.png)

The other one never expands.

**Comment by nitishsharma25** [comment]
@aasimkhan30 I see the issue, will be fixed in the next release, thanks

**Comment by aasimkhan30** [comment]
@nitishsharma25 and @rishky-msft  I am working on a new OE implementation in ads and I have noticed this issue quite a lot. Also, if you keep connecting and disconnecting the same connection, it fails to create a session with this error.
