### ISSUE TITLE
not able to expand a server in both servers view and azure view at the same time

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio-mysql#78]
If I connect to a server in servers view or azure view, then I won't be able to open it in the other view.

![image](https://user-images.githubusercontent.com/13777222/194372376-4ef02ee7-2403-46cc-8424-2263151054eb.png)

mssql doesn't have such problem.

**Comment by rishky-msft** [comment]
@alanrenmsft 

The behaviour is common across all extensions and needs to be controlled at ADS end.
Resolving the issue at MySQL side.
