### ISSUE TITLE
Script as Create does not work on Stored Procedures and Functions

### ISSUE THREAD

**Issue by lukaspieza** [microsoft/azuredatastudio-mysql#81]
Hi,
Script as Create does not work on Stored Procedures and Functions. it returns Scripting Failed. Works with Views and Tables.

![image](https://user-images.githubusercontent.com/33227448/196050426-de9972f5-d8ac-4703-a330-c839146894e4.png)

**Comment by rishky-msft** [comment]
Hi @lukaspieza,

Can you please add more details to the issue.
ADS version
OS version
Platform

**Comment by lukaspieza** [comment]
Hi @rishky-msft,
I have used ADS 1.40.0 insider edition zip https://sqlopsbuilds.azureedge.net/insider/684556b1ff570cc7f85facdfd5d943a15938a436/azuredatastudio-windows-1.40.0-insider.zip
Edition	Windows 10 Pro
Version	21H2
Installed on	‎2021-‎04-‎10
OS build	19044.2130
Experience	Windows Feature Experience Pack 120.2212.4180.0
And used vsix to import mysql extension [azuredatastudio-mysql-0.2.2-win-x64.vsix](https://github.com/microsoft/azuredatastudio-mysql/releases/download/v0.2.2/azuredatastudio-mysql-0.2.2-win-x64.vsix)
 105 MB
[rishky-msft](https://github.com/rishky-msft) released this 5 days ago [ v0.2.2](https://github.com/microsoft/azuredatastudio-mysql/tree/v0.2.2) 8821dbb

**Comment by lukaspieza** [comment]
ADS link is taken from https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main

**Comment by rishky-msft** [comment]
@lukaspieza

Can you run the scenario once again in ADS and share me the logs.
Logpath : C:\Users\<user-name>\AppData\Roaming\sqlops\MySQL\ossdbtoolsservice.log

**Comment by lukaspieza** [comment]
@rishky-msft here is your requested log.
[ossdbtoolsservice.log](https://github.com/microsoft/azuredatastudio-mysql/files/9802086/ossdbtoolsservice.log)

**Comment by rishky-msft** [comment]
@lukaspieza

I am not able to reproduce the issue. It is working fine for me with same environment details as you shared.

Even in the mysql extension logs the operation is success.
2022-10-17 18:26:44,470 INFO Received request id=8 method=scripting/script
2022-10-17 18:26:44,528 INFO ResponseSuccess message sent id=8 method=None

Is this an intermittent issue or are you facing this always?

Engaged the ADS team to help out here.

**Comment by rishky-msft** [comment]
@lukaspieza
Yeah, will fix this with in the next release.
