### ISSUE TITLE
"Unpack requires a buffer of 4 bytes" exception when returning bit(1) column

### ISSUE THREAD

**Issue by jonahflor** [microsoft/azuredatastudio-mysql#82]
When returning a bit(1) column in a query, the following exception is thrown:

Request query/subset failed.
  Message: Unhandled exception while handling request method query/subset: "unpack requires a buffer of 4 bytes"
  Code: -32603

**Comment by jonahflor** [comment]
Casting as SIGNED or UNSIGNED is a workaround, but it's inconvenient to have to do this for specific columns rather than selecting *.

**Comment by rishky-msft** [comment]
@jonahflor 

You can try this vsix on windows and confirm if the issue is fixed for you.
https://github.com/microsoft/azuredatastudio-mysql/releases/download/v0.2.3-alpha.1/azuredatastudio-mysql-0.2.3-alpha.1.vsix

**Comment by rishky-msft** [comment]
The changes will be available in the next release 0.2.3 of
https://github.com/microsoft/azuredatastudio-mysql
