### ISSUE TITLE
cannot connect to freemysqlhosting.net

### ISSUE THREAD

**Issue by yazilim4** [microsoft/azuredatastudio-mysql#84]
Hello

I created a new mysql database on https://www.freemysqlhosting.net. And while connection this database on azure datastudio when I receive an error that (1043, 'Bad handshake')i

Steps to Reproduce:

1. Create a mysql database on https://www.freemysqlhosting.net 
2. Try to connect this database on AzureDataStudio Insiders.

**Comment by alanrenmsft** [comment]
@yazilim4 I've transfered your issue to the correct repository, please open mysql issues in this repo.

**Comment by rishky-msft** [comment]
@yazilim4 
You have to set the SSL Mode to Disabled as cheenamalhotra mentioned.

**Comment by yazilim4** [comment]
Thanks for helping.
