### ISSUE TITLE
Bad Handshake when connecting to local MySql, on MacOS

### ISSUE THREAD

**Issue by stimocea** [microsoft/azuredatastudio-mysql#88]
Azure Data Studio Version: 1.41.0-insider, 1.41.0
Extension: MySQL v0.2.4, v0.2.3
OS: MacOS Ventura (13.0.1) or  MacOS Monterey 

Extension successfully installed
MySQL Tools Service started

Trying to create a new connection of type MySql, to Server: localhost, user name: root, password _password for root user here_

Error Message : Bad handshake
ErrorCode : 1043

Connecting to the exact same MySQL server, with the same user & password, from a different client works fine.

**Comment by rishky-msft** [comment]
Hi @stimocea,

Can you try connecting without SSL from ADS?
To disable ssl, In the connection dialog,
Goto Advanced Configuration and set SSL mode to Disable.

Also,
When connecting with other clients,
Can you provide the output of below query?
SHOW STATUS LIKE 'Ssl_cipher';

This will help in checking if you are connected with SSL

**Comment by stimocea** [comment]
It's a miracle! 

Hi @rishky-msft , thanks for your reply!

Yes, it connects successfully to the MySQL server indeed, when I disable the SSL for the connection
and It seems that the query `SHOW STATUS LIKE 'Ssl_cipher';` into the other client indicates retrieves the below value:
| Variable_name | Value |
| ------------- | ----- |
| Ssl_cipher    |       |

However, when tested on Windows, there's no similar issue (I don't have to disable connection SSL) and the similar query returns
| Variable_name | Value                  |
| ------------- | ---------------------- |
| Ssl_cypher    | TLS_AES_256_GCM_SHA384 |

Is my MySQL server missing something (SSL?) on MacOS ?

**Comment by rishky-msft** [comment]
Empty Ssl_cipher means that your local mysql server is getting connected without SSL for other clients as well.

@stimocea,
Seems like youe MySql server ssl configuration has some issues on your Mac Machine.
