### ISSUE TITLE
Error: Failed to expand node when clicking on a database to expand it

### ISSUE THREAD

**Issue by aj-enns** [microsoft/azuredatastudio-mysql#92]
I have one Server using Azure Database for MySQL.  Inside that server, I have 4 user db's. Inside ADS, I am able to expand two of them, but two of them I get: Error: Failed to expand node when trying to expand them.  The data is fine inside these two databases and I can query them, I just can't use the server explorer to expand them.  I originally thought it was because I created the db using another application, but then dropped it and created it within ADS.  It stills gives the error when expanding.

Host OS: Ventura 13.1 with arm
ADS 1.40.1

<img width="994" alt="Screenshot 2022-12-22 at 1 11 49 PM" src="https://user-images.githubusercontent.com/6963265/209209542-52c0ca09-ec2d-481a-86e6-0290499cd7f3.png">

**Comment by aj-enns** [comment]
well I just figured out my own issue, but want to update this issue as it might help others.  The two databases that didn't work contained a "-" in the name.  Once I replaced the "-" with a "_" I was able to expand the databases just fine.  Both characters are legal characters in Mysql naming conventions.

**Comment by rishky-msft** [comment]
@aj-enns Yeah this fix we have already done. It will be available with the next release.
